# MOSQUITTO CONFIG VARS

MOSQUITTO_TOPIC = "changeit"
MOSQUITTO_HOST = "changeit"
MOSQUITTO_PORT = changeit
MOSQUITTO_RECONNECT = changeit
MOSQUITTO_USER = "changeit"
MOSQUITTO_PASSWORD = "changeit"

#DATABSE CONFIG VARS
MONGO_HOST = "changeit"
